name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Install backend dependencies
        run: |
          cd backend
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Run frontend unit tests
        run: |
          cd frontend
          npm test -- --coverage --watchAll=false
      - name: Run backend unit tests
        run: |
          cd backend
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings --cov=.

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Run Cypress E2E tests
        run: |
          cd frontend
          npx cypress run

  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      - name: Run Lighthouse CI
        run: |
          npx lhci autorun --upload.target=temporary-public-storage
