apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notes-helper.fullname" . }}
  labels:
    app: {{ include "notes-helper.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "notes-helper.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "notes-helper.name" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET | quote }}
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
          ports:
            - containerPort: 8000
