apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "notes-helper.fullname" . }}-migrate
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["alembic", "upgrade", "head"]
          env:
            - name: JWT_SECRET
              value: {{ .Values.env.JWT_SECRET | quote }}
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
